FROM    debian:bullseye

RUN     apt update -y && apt upgrade -y && apt install -y \
            nginx \
            openssl && \
        mkdir -p /etc/nginx/ssl /var/run/nginx && \
        openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42/OU=42/CN=leochen.42.fr/UID=leochen" && \
        chmod 755 /var/www/html && \
        chown -R www-data:www-data /var/www/html

EXPOSE  443

COPY    conf/nginx.conf /etc/nginx/nginx.conf

CMD     ["nginx", "-g", "daemon off;"]
